# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3992022edbba40672e6b70a34443ba400a812878ed9c0155673750bcbb067e82a2dace24c1261f3f73887f7f17fe8e6ad46e6ed3606529ab5047433fb25119d8

test:
  secret_key_base: 5c647db424dd0c32178a109060389534e5d20b01cd65369f3315f74280938558ddbdb809b6043604eb40c782a96cc7a090f612472739656c48ba840edfc2f23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
